POST http://localhost:3333/events
content-type: application/json

{
    "title": "don toliver show",
    "details": "we don't need details shit"

}

###
POST http://localhost:3333/events/8157b08f-bab0-4115-b2d9-a0f6617e8837/attendee
content-type: application/json

{
    "name": "joão",
    "email": "jao@gmail.com"
}

###
GET  http://localhost:3333/events/8157b08f-bab0-4115-b2d9-a0f6617e8837

###
GET  http://localhost:3333/events/show-em-east-abdielfort-eVKJ2p/attendees?limit=8&pageIndex=0



###
GET  http://localhost:3333/events/attendee/13/badge

###
GET http://localhost:3333/attendees/12/check-in

###
DELETE http://localhost:3333/attendees/1404

### authentication 

POST  http://localhost:3333/auth/google/redirect-url

###
POST  http://localhost:3333/auth/sign-up

